name: IssueOps Validator

on:
  issues:
    types: [opened, edited]

permissions:
  contents: read
  issues: write

concurrency:
  group: issue-validator-${{ github.event.issue.number || github.ref }}
  cancel-in-progress: true

jobs:
  issue-ops-validator:
    name: IssueOps Validator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Parse Issue Body
        id: parse
        uses: issue-ops/parser@v4.0.0
        with:
          body: ${{ github.event.issue.body }}

      - name: IssueOps Validator
        id: validate
        uses: issue-ops/validator@v4.0.0
        with:
          issue-number: ${{ github.event.issue.number }}
          parsed-issue-body: ${{ steps.parse.outputs.json }}
