name: Sponsor Labels

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  sponsor-label:
    name: Sponsor Labels
    runs-on: ubuntu-latest
    steps:
      - name: Sponsor Labels
        uses: JasonEtco/is-sponsor-label-action@v2.0.0
        with:
          label: "Sponsor ❤️"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
